/**
 * Ambient type declarations for `@arduino/arduino-iot-client` (v3.0.0).
 *
 * The package is auto-generated by OpenAPI Generator and ships no TypeScript
 * definitions. We only type the narrow surface consumed by this package;
 * anything not covered here stays `any` under the module fallback.
 */
declare module '@arduino/arduino-iot-client' {
  interface AuthenticationSlot {
    accessToken: string;
  }

  export class ApiClient {
    constructor();
    static instance: ApiClient;
    authentications: {
      oauth2: AuthenticationSlot;
      [key: string]: AuthenticationSlot;
    };
  }

  interface CommonOpts {
    xOrganization?: string;
  }

  export interface ArduinoThing {
    id: string;
    name: string;
    device_id?: string;
    device_name?: string;
    device_fqbn?: string;
    device_type?: string;
    properties_count?: number;
    organization_id?: string;
    sketch_id?: string;
    tags?: string[];
    timezone?: string;
    user_id?: string;
    created_at?: string;
    updated_at?: string;
  }

  export interface ArduinoProperty {
    id: string;
    name: string;
    variable_name: string;
    type: string;
    permission: string;
    last_value?: unknown;
    value_updated_at?: string;
    thing_id?: string;
    thing_name?: string;
    persist?: boolean;
    tag?: number;
    href?: string;
    sync_id?: string;
    update_strategy?: string;
    update_parameter?: number;
    min_value?: number;
    max_value?: number;
    linked_to_trigger?: string;
    created_at?: string;
    updated_at?: string;
  }

  export class ThingsV2Api {
    constructor(apiClient?: ApiClient);
    thingsV2List(opts?: CommonOpts & {
      acrossUserIds?: boolean;
      deviceId?: string;
      ids?: string[];
      showDeleted?: boolean;
      showProperties?: boolean;
      tags?: string[];
    }): Promise<ArduinoThing[]>;
  }

  export class PropertiesV2Api {
    constructor(apiClient?: ApiClient);
    propertiesV2List(
      id: string,
      opts?: CommonOpts & { showDeleted?: boolean },
    ): Promise<ArduinoProperty[]>;
    propertiesV2Show(
      id: string,
      pid: string,
      opts?: CommonOpts & { showDeleted?: boolean },
    ): Promise<ArduinoProperty>;
    propertiesV2Publish(
      id: string,
      pid: string,
      propertyValue: { value: unknown; device_id?: string },
      opts?: CommonOpts,
    ): Promise<void>;
  }

  export interface HistoricDataRequest {
    from: Date;
    to: Date;
    properties: string[];
  }

  export interface ArduinoSeriesResponse {
    aggregation?: string;
    count_values?: number;
    from_date?: Date | string;
    to_date?: Date | string;
    interval?: number;
    message?: string;
    property_id?: string;
    property_name?: string;
    property_type?: string;
    query?: string;
    resp_version?: number;
    series_limit?: number;
    status?: string;
    thing_id?: string;
    times?: Array<Date | string>;
    values?: number[];
  }

  export interface ArduinoSeriesBatch {
    resp_version?: number;
    responses?: ArduinoSeriesResponse[];
  }

  export class SeriesV2Api {
    constructor(apiClient?: ApiClient);
    seriesV2HistoricData(
      historicDataRequest: HistoricDataRequest,
      opts?: CommonOpts,
    ): Promise<ArduinoSeriesBatch>;
  }

  // Deliberately no `default` export — the SDK's CJS entry marks itself as
  // an ES module (`__esModule: true`) but never assigns `exports.default`.
  // Using `import X from '@arduino/arduino-iot-client'` would resolve to
  // `undefined` under esbuild's interop and crash every SDK call at runtime.
}
