#!/usr/bin/env bash
# Install the autossh reverse-SSH client on a Q.
#
# Rsyncs the q/ container assets and ships two cert/key bundles to the Q:
#   - The device's user-cert + private key (from pki/out/devices/<device>/).
#   - The n8n endpoint's host pubkey (from pki/out/n8n/<n8n>/), used by
#     autossh's known_hosts for fingerprint pinning. There is no host cert
#     in this design — see master-plan §14.2 follow-up.
#
# A device cert is reusable across n8n endpoints: this script binds them
# together at install time, not at issuance time. To re-point a device at a
# different n8n endpoint, re-run with a new --n8n.
#
# Writes a .env with the n8n endpoint coordinates, then runs
# `docker compose up -d`. Idempotent — safe to re-run after a re-issue or
# an endpoint change.
#
# Prerequisites:
#   - Run ./pki/pki setup once (first time only)
#   - Run ./pki/pki add device <device-nick> for this Q
#   - Run ./pki/pki add n8n <n8n-nick>          on the same PC
#
# Usage:
#   ./install.sh --device <nick> --n8n <nick> --n8n-host <hostname>
#                [--n8n-port <port>] [--host <user@q-host>]
#
# Host resolution (target Q):
#   1. --host <user@host>
#   2. UNOQ_HOST env var
#   3. arduino@linucs.local (default)
#
# Other env overrides:
#   UNOQ_BASE=/home/arduino           → base dir on the Q
#   UNOQ_REMOTE_BIND_PORT=7000        → -R bind port; arbitrary, not a routing key
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=../lib/ssh-multiplex.sh
source "$DEPLOY_DIR/lib/ssh-multiplex.sh"

DEVICE=""
N8N_NICK=""
N8N_HOST=""
N8N_SSH_PORT=""
HOST_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --device)     DEVICE="$2"; shift 2 ;;
    --device=*)   DEVICE="${1#*=}"; shift ;;
    --n8n)        N8N_NICK="$2"; shift 2 ;;
    --n8n=*)      N8N_NICK="${1#*=}"; shift ;;
    --n8n-host)   N8N_HOST="$2"; shift 2 ;;
    --n8n-host=*) N8N_HOST="${1#*=}"; shift ;;
    --n8n-port)   N8N_SSH_PORT="$2"; shift 2 ;;
    --n8n-port=*) N8N_SSH_PORT="${1#*=}"; shift ;;
    --host)       HOST_OVERRIDE="$2"; shift 2 ;;
    --host=*)     HOST_OVERRIDE="${1#*=}"; shift ;;
    -h|--help|help)
      cat <<EOF
Usage: $(basename "$0") --device <nick> --n8n <nick> --n8n-host <hostname>
                       [--n8n-port <port>] [--host <user@q-host>]

Deploys the reverse-SSH relay using a device cert previously issued by
./pki/pki add device <nick> and binds it to a specific n8n endpoint
previously generated by ./pki/pki add n8n <n8n-nick>.

Options:
  --device <nick>         (required) Which device cert bundle to push.
  --n8n <nick>            (required) Which n8n endpoint to bind this Q to.
                          Picks the host pubkey from pki/out/n8n/<nick>/.
  --n8n-host <hostname>   (required) Hostname (or IP) the Q's autossh dials.
  --n8n-port <port>       (optional) TCP port. Default 2222.
  --host <user@q-host>    Override target Q for this invocation.
                          Falls back to UNOQ_HOST env, then 'arduino@linucs.local'.
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      echo "Usage: $(basename "$0") --device <nick> --n8n <nick> --n8n-host <h> [--n8n-port <p>] [--host <user@q-host>]" >&2
      exit 1
      ;;
  esac
done
[ -n "$HOST_OVERRIDE" ] && HOST="$HOST_OVERRIDE"

if [ -z "$DEVICE" ]; then
  echo "error: --device <nickname> is required." >&2; exit 1
fi
if [ -z "$N8N_NICK" ]; then
  echo "error: --n8n <nickname> is required." >&2
  echo "Run ./pki/pki add n8n <nick> first to generate the host keypair." >&2
  exit 1
fi
if [ -z "$N8N_HOST" ]; then
  echo "error: --n8n-host <hostname> is required (the address the Q dials)." >&2; exit 1
fi

DEVICE_BUNDLE="$SCRIPT_DIR/pki/out/devices/$DEVICE"
if [ ! -d "$DEVICE_BUNDLE" ]; then
  echo "error: no device bundle at $DEVICE_BUNDLE" >&2
  echo "Run: $SCRIPT_DIR/pki/pki add device $DEVICE" >&2
  exit 1
fi
for f in id_ed25519 id_ed25519-cert.pub; do
  if [ ! -f "$DEVICE_BUNDLE/$f" ]; then
    echo "error: $DEVICE_BUNDLE/$f is missing — re-run ./pki add device $DEVICE" >&2
    exit 1
  fi
done

N8N_BUNDLE="$SCRIPT_DIR/pki/out/n8n/$N8N_NICK"
if [ ! -d "$N8N_BUNDLE" ]; then
  echo "error: no n8n bundle at $N8N_BUNDLE" >&2
  echo "Run: $SCRIPT_DIR/pki/pki add n8n $N8N_NICK" >&2
  exit 1
fi
HOST_PUB="$N8N_BUNDLE/ssh_host_ed25519_key.pub"
if [ ! -f "$HOST_PUB" ]; then
  echo "error: $HOST_PUB is missing — re-run ./pki add n8n $N8N_NICK" >&2
  exit 1
fi

REMOTE_DIR="$REMOTE_BASE/relay-ssh"
N8N_SSH_PORT="${N8N_SSH_PORT:-2222}"
REMOTE_BIND_PORT="${UNOQ_REMOTE_BIND_PORT:-7000}"

echo "Installing reverse-SSH relay for device '$DEVICE' on $HOST..."
echo "  → n8n endpoint: $N8N_HOST:$N8N_SSH_PORT (cert nick '$N8N_NICK')"
echo "  → pinned host pubkey: $(ssh-keygen -lf "$HOST_PUB" | awk '{print $2}')"

ssh "${SSH_OPTS[@]}" "$HOST" "mkdir -p $REMOTE_DIR/certs"

# Sync the Q-side container assets under q/. Excludes certs/ — populated
# separately below with the device cert + pinned host pubkey.
rsync -av --delete -e "$SSH_CMD" \
  --exclude certs \
  "$SCRIPT_DIR/q/" "$HOST:$REMOTE_DIR/"

# Push the device cert bundle (private key + cert).
rsync -av -e "$SSH_CMD" \
  "$DEVICE_BUNDLE/id_ed25519" \
  "$DEVICE_BUNDLE/id_ed25519-cert.pub" \
  "$HOST:$REMOTE_DIR/certs/"

# Push the pinned n8n host pubkey, renamed so the entrypoint script knows
# what to look for.
rsync -av -e "$SSH_CMD" \
  "$HOST_PUB" "$HOST:$REMOTE_DIR/certs/n8n_host.pub"

# Write the .env file docker-compose reads.
ssh "${SSH_OPTS[@]}" "$HOST" "cat > $REMOTE_DIR/.env" <<EOF
N8N_HOST=$N8N_HOST
N8N_SSH_PORT=$N8N_SSH_PORT
REMOTE_BIND_PORT=$REMOTE_BIND_PORT
EOF

# `up -d` reconciles config; `restart` forces autossh to pick up freshly
# rsynced certs (it reads them once at startup).
ssh "${SSH_OPTS[@]}" "$HOST" "
  cd $REMOTE_DIR && \
  docker compose up -d && \
  docker compose restart unoq-relay-ssh
"

cat <<EOF

✓ Reverse-SSH relay running on $HOST as device '$DEVICE'
  Bound to n8n endpoint '$N8N_NICK' at $N8N_HOST:$N8N_SSH_PORT
  Tunnel will surface on the n8n side as 127.0.0.1:$REMOTE_BIND_PORT (per registry, keyed by '$DEVICE')

Next steps:
  1. On the n8n host, ensure port $N8N_SSH_PORT is reachable from the Q
     (or wherever this Q sits). See deploy/relay-ssh/n8n-server/README.md.

  2. In n8n, create an "Arduino UNO Q SSH Relay" credential:
     Listen address:        0.0.0.0
     Listen port:           $N8N_SSH_PORT
     Host private key:      paste $N8N_BUNDLE/ssh_host_ed25519_key
     User CA public key:    paste $N8N_BUNDLE/user_ca.pub
     Required principal:    tunnel
     Device nickname:       $DEVICE

  3. Click "Test Connection" — it looks up '$DEVICE' in the registry and
     calls \$/version through the tunnel.

Verify manually (optional):
  ssh $HOST 'docker compose -f $REMOTE_DIR/docker-compose.yml ps'
  ssh $HOST 'docker compose -f $REMOTE_DIR/docker-compose.yml logs --tail=20 unoq-relay-ssh'

Re-bind this device to a different n8n endpoint:
  $(basename "$0") --device $DEVICE --n8n <other-nick> --n8n-host <other-hostname>
EOF
